# Generated by Django 4.2.1 on 2023-07-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('lock_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('lock_name', models.CharField(max_length=100)),
                ('lock_alias', models.CharField(max_length=100)),
                ('lock_mac', models.CharField(max_length=100)),
                ('key_id', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='hashed_password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
