# Generated by Django 4.2.1 on 2023-08-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lock_user_hashed_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ttlock_username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
