# Generated by Django 4.2.1 on 2023-08-09 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('alarm_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('receiver', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Lock', 0), ('Unlock', 1), ('Warning', 2)], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ekey',
            fields=[
                ('ekey_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('remarks', models.TextField(null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lock_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.group')),
            ],
        ),
        migrations.CreateModel(
            name='Lock_Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passcode',
            fields=[
                ('passcode_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('passcode', models.TextField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('One-time', 'One-time'), ('Permanent', 'Permanent'), ('Timed', 'Timed'), ('Custom', 'Custom'), ('Recurring', 'Recurring'), ('Erase', 'Erase')], max_length=50)),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Lock', 0), ('Unlock', 1), ('Failed', 2)], max_length=50)),
                ('method', models.CharField(choices=[('App', 'App'), ('Pin', 'Pin')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('birth_date', models.DateField(auto_now_add=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.RenameField(
            model_name='lock',
            old_name='lock_alias',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='lock',
            name='key_id',
        ),
        migrations.RemoveField(
            model_name='lock',
            name='lock_mac',
        ),
        migrations.RemoveField(
            model_name='lock',
            name='lock_name',
        ),
        migrations.AlterField(
            model_name='lock',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lock',
            name='lock_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('DELIVERY', 'Delivery')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='record',
            name='lock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lock'),
        ),
        migrations.AddField(
            model_name='passcode',
            name='lock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lock'),
        ),
        migrations.AddField(
            model_name='lock_owner',
            name='lock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lock'),
        ),
        migrations.AddField(
            model_name='lock_owner',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lock_group',
            name='lock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lock'),
        ),
        migrations.AddField(
            model_name='ekey',
            name='lock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lock'),
        ),
        migrations.AddField(
            model_name='ekey',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alarm',
            name='lock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lock'),
        ),
    ]
