# Generated by Django 4.2.1 on 2023-08-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_passcode_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passcode',
            name='passcode',
            field=models.IntegerField(max_length=15),
        ),
    ]
