# Generated by Django 4.2.1 on 2023-11-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_passcode_passcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sex',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Prefer not to say')], null=True),
        ),
        migrations.AlterField(
            model_name='passcode',
            name='passcode',
            field=models.IntegerField(),
        ),
    ]
