# Generated by Django 4.2.1 on 2023-11-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_userprofile_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.AddField(
            model_name='notification',
            name='keyboardPwd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='lockDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='lockId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='recordType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='success',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
