# Generated by Django 4.2.1 on 2023-11-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_location_name_location_lock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
