# Generated by Django 4.2.1 on 2023-11-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_message_delete_notification_remove_record_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Notification',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='message_id',
            new_name='notification_id',
        ),
    ]
